<a href="https://colab.research.google.com/github/cranialsurge/learningpythonfordatascience/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arrays

## Create an array

In [2]:
import numpy as np

In [2]:
# create array
l = [1.0, 2.0, 3.0]
a = np.array(l)
# display array
print(a)
# display array shape
print(a.shape)
# display array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


## Functions to create arrays

In [3]:
# create empty array
a = np.empty([3,3])
print(a)

[[ 3.45126646e-31 -6.90253292e-31  1.72563323e-31]
 [-6.90253292e-31  1.50130091e-30 -4.65920972e-31]
 [ 1.72563323e-31 -4.65920972e-31  2.67473151e-31]]


In [5]:
# create zero array
a = np.zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
# create one array
a = np.ones([5])
print(a)

[1. 1. 1. 1. 1.]


## Combining arrays

### Vertical stack(vstack)

In [7]:
# create array with vstack
# create first array
a1 = np.array([1,2,3])
print(a1)
# create second array
a2 = np.array([4,5,6])
print(a2)
# vertical stack
a3 = np.vstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


### Horizontal Stack(hstack)

In [8]:
# create array with hstack
# create first array
a1 = np.array([1,2,3])
print(a1)
# create second array
a2 = np.array([4,5,6])
print(a2)
# create horizontal array
a3 = np.hstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)


## From 1D list to array

In [5]:
# create 1D array
data = [11, 22, 33, 44, 55]
print(type(data))
# array of data
data = np.array(data)
print(data)
print(type(data))

<class 'list'>
[11 22 33 44 55]
<class 'numpy.ndarray'>


In [6]:
# create 3D array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
print(type(data))
# array of data
data = np.array(data)
print(data)
print(type(data))

<class 'list'>
[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


## Array indexing

In [13]:
# define array
data = np.array([11, 22, 33, 44, 55])
# index data
print(data[0])
print(data[4])
# you can use negative indices to retrieve values offset from the end of the array. 
# for example, the index -1 refers to the last item in the array, -2 the second last item and so on.
print(data[-1])
print(data[-4])

11
55
55
22


In [18]:
# index 2D array
from numpy import array
# define array
data = array([
[11, 22],
[33, 44],
[55, 66]])
# index data
print(data[0,0])
print(data[1,1])
# all items in the first row
print(data[0,])
# all items in the third row
print(data[2,])

11
44
[11 22]
[55 66]


## Slicing

### Slicing is specified using the colon operator : with a from and to index before and after the column respectively.
### The slice extends from the from index and ends one item before the to index.

In [26]:
# slice a 1D array
# define array
data = np.array([11, 22, 33, 44, 55])
# this prints all elements in the array
print(data[:])
# this prints the first item in the array
print(data[0:1])
# this prints the last 2 items in the array using -ve indices
print(data[-2:-1])

[11 22 33 44 55]
[11]
[44]


## Split input and output features

It is common to split your loaded data into input variables (X) and the output variable (y). We
can do this by slicing all rows and all columns up to, but before the last column, then separately
indexing the last column. For the input features, we can select all rows and all columns except
the last one by specifying : for in the rows index, and :-1 in the columns index.

### X = [:, :-1]

For the output column, we can select all rows again using : and index just the last column
by specifying the -1 index.

### y = [:, -1]

In [27]:
# split input and output data
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
X, y = data[:, :-1], data[:, -1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


## Split train and test rows

It is common to split a loaded dataset into separate train and test sets. This is a splitting of
rows where some portion will be used to train the model and the remaining portion will be used
to estimate the skill of the trained model. This would involve slicing all columns by specifying :
in the second dimension index. The training dataset would be all rows from the beginning to
the split point.

### train = data[:split, :]

In [28]:
# split train and test data
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
split = 2
train,test = data[:split,:],data[split:,:]
print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


## Array Reshaping

### Data Shape

In [33]:
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)

# shape of a 2D array
data = array([
    [11, 22],
    [33, 44],
    [55, 66]
])
print(data.shape)

# The elements of the .shape tuple can be accessed just like an array, with the 0th index for
# the number of rows and the 1st index for the number of columns.
print('Rows:', data.shape[0])
print('Cols:', data.shape[1])

(5,)
(3, 2)
Rows: 3
Cols: 2


## Reshape 1D to 2D Array

It is common to need to reshape a one-dimensional array into a two-dimensional array with
one column and multiple rows. NumPy provides the reshape() function on the NumPy array
object that can be used to reshape the data. The reshape() function takes a single argument
that specifies the new shape of the array. In the case of reshaping a one-dimensional array into
a two-dimensional array with one column, the tuple would be the shape of the array as the first
dimension (data.shape[0]) and 1 for the second dimension.

### data = data.reshape((data.shape[0], 1))

In [36]:
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)
print('Original shape', data)
#reshape
data = data.reshape((data.shape[0], 1))
print(data.shape)
print('Reshaped form', data)

(5,)
Original shape [11 22 33 44 55]
(5, 1)
Reshaped form [[11]
 [22]
 [33]
 [44]
 [55]]


## Reshape 2D to 3D Array

It is common to need to reshape two-dimensional data where each row represents a sequence
into a three-dimensional array for algorithms that expect multiple samples of one or more time
steps and one or more features. A good example is the LSTM recurrent neural network model
in the Keras deep learning library. The reshape function can be used directly, specifying the
new dimensionality. This is clear with an example where each sequence has multiple time steps
with one observation (feature) at each time step. We can use the sizes in the shape attribute on
the array to specify the number of samples (rows) and columns (time steps) and  x the number
of features at 1.

### data.reshape((data.shape[0], data.shape[1], 1))

In [40]:
# array of data
data = array([
    [11, 22],
    [33, 44],
    [55, 66]
    ])
print('Original shape: ', data.shape)
print('Original form: ', data)

# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print('Reshaped shape: ', data.shape)
print('Reshaped form: ', data)

Original shape:  (3, 2)
Original form:  [[11 22]
 [33 44]
 [55 66]]
Reshaped shape:  (3, 2, 1)
Reshaped form:  [[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]


## Array Broadcasting

Arrays with different sizes cannot be added, subtracted, or generally be used in arithmetic. A
way to overcome this is to duplicate the smaller array so that it has the dimensionality and
size as the larger array. This is called array broadcasting and is available in NumPy when
performing array arithmetic, which can greatly reduce and simplify your code.

### Limitation with Array Arithmetic

You can perform arithmetic directly on NumPy arrays, such as addition and subtraction. For
example, two arrays can be added together to create a new array where the values at each
index are added together. For example, an array a can be de ned as [1; 2; 3] and array b can be
de ned as [1; 2; 3] and adding together will result in a new array with the values [2; 4; 6].

a = [1, 2, 3]

b = [1, 2, 3]

c = a + b

c = [1 + 1, 2 + 2, 3 + 3]

Strictly, arithmetic may only be performed on arrays that have the same dimensions and
dimensions with the same size. This means that a one-dimensional array with the length of
10 can only perform arithmetic with another one-dimensional array with the length 10. This
limitation on array arithmetic is quite limiting indeed. Thankfully, NumPy provides a built-in
workaround to allow arithmetic between arrays with di ering sizes.