# Matrices

## Define a matrix

In [3]:
import numpy as np

In [4]:
# create matrix
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


## Matrix Arithmetic

Operations are performed element-wise between two matrices of equal size to result in a new matrix with the
same size.

### Matrix Addition

Two matrices with the same dimensions can be added together to create a new third matrix.

C = A + B

The scalar elements in the resulting matrix are calculated as the addition of the elements in
each of the matrices being added.

In [5]:
# define first matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A)

# define second matrix
B = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(B)

# add matrices
C = A + B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


### Matrix Subtraction

Similarly, one matrix can be subtracted from another matrix with the same dimensions.

C = A - B

The scalar elements in the resulting matrix are calculated as the subtraction of the elements
in each of the matrices.

In [6]:
# define first matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A)

# define second matrix
B = np.array([
    [0.5, 0.5, 0.5],
    [0.5, 0.5, 0.5]
])
print(B)

# subtract matrices
C = A - B
print(C)

[[1 2 3]
 [4 5 6]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
[[0.5 1.5 2.5]
 [3.5 4.5 5.5]]


### Matrix Multiplication(Hadamard Product)

Two matrices with the same size can be multiplied together, and this is often called element-wise
matrix multiplication or the Hadamard product. It is not the typical operation meant when
referring to matrix multiplication, therefore a di erent operator is often used, such as a circle o.

C = A o B

As with element-wise subtraction and addition, element-wise multiplication involves the
multiplication of elements from each parent matrix to calculate the values in the new matrix.

In [7]:
# define first matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A)

# define second matrix
B = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(B)

# multiply matrices
C = A * B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]


### Matrix Division

One matrix can be divided by another matrix with the same dimensions.

C = A / B

The scalar elements in the resulting matrix are calculated as the division of the elements in
each of the matrices.

In [8]:
# define first matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A)

# define second matrix
B = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(B)

# divide matrices
C = A / B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1. 1. 1.]
 [1. 1. 1.]]


### Matrix-Matrix Multiplication

Matrix multiplication, also called the matrix dot product is more complicated than the previous
operations and involves a rule as not all matrices can be multiplied together.

C = A.B

or

C = AB

The rule for matrix multiplication is as follows:

 -- The number of columns (n) in the first matrix (A) must equal the number of rows (m) in
the second matrix (B).

For example, matrix A has the dimensions m rows and n columns and matrix B has the dimensions n and k.
The n columns in A and n rows in B are equal. The result is a new matrix with m rows and k columns.

C(m, k) = A(m, n) . B(n, k)

This rule applies for a chain of matrix multiplications where the number of columns in one
matrix in the chain must match the number of rows in the following matrix in the chain.

One of the most important operations involving matrices is multiplication of two
matrices. The matrix product of matrices A and B is a third matrix C. In order for
this product to be defined, A must have the same number of columns as B has rows.
If A is of shape m x n and B is of shape n x p, then C is of shape m x p.

The intuition for the matrix multiplication is that we are calculating the dot product between
each row in matrix A with each column in matrix B. For example, we can step down rows of
column A and multiply each with column 1 in B to give the scalar values in column 1 of C.


In [9]:
#  define first matrix
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(A)

#  define second matrix
B = np.array([
    [1, 2],
    [3, 4]
])
print(B)

# multiple matrices
C = A.dot(B)
print(C)

# multiply matrices with @ operator. The '@' operator is newer and can be used as a replacement for .dot()
D = A @ B
print(D)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]
 [23 34]]
[[ 7 10]
 [15 22]
 [23 34]]


### Matrix-Vector Multiplication

A matrix and a vector can be multiplied together as long as the rule of matrix multiplication
is observed. Specifically, that the number of columns in the matrix must equal the number of
items in the vector. As with matrix multiplication, the operation can be written using the dot
notation. Because the vector only has one column, the result is always a vector.

c = A . v

or

c = Av

In [11]:
# define matrix
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(A)

# define vector
B = np.array([0.5, 0.5])
print(B)

# multiply
C = A.dot(B)
print(C)

[[1 2]
 [3 4]
 [5 6]]
[0.5 0.5]
[1.5 3.5 5.5]


### Matrix-Scalar Multiplication

A matrix can be multiplied by a scalar. This can be represented using the dot notation between
the matrix and the scalar.

C = A . b

or

C = Ab

The result is a matrix with the same size as the parent matrix where each element of the
matrix is multiplied by the scalar value.

In [12]:
# define matrix
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(A)

# define scalar
b = 0.5
print(b)

# multiply
C = A * b
print(C)

[[1 2]
 [3 4]
 [5 6]]
0.5
[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]
