In [1]:
import numpy as np

# Tensors

A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional
array. It is a container of data. 

A vector is a one-dimensional or first order tensor and a matrix is a two-dimensional or second
order tensor.

Many of the operations that can be performed with scalars, vectors, and matrices can be
reformulated to be performed with tensors. As a tool, tensors and tensor algebra is widely
used in the  elds of physics and engineering. Some operations in machine learning such as the
training and operation of deep learning models can be described in terms of tensors.

In [4]:
# Like vectors and matrices, tensors can be represented in Python using the N-dimensional array
# (ndarray). A tensor can be defined in-line to the constructor of array() as a list of lists. The
# example below defines a 3 x 3 x 3 tensor as a NumPy ndarray. Three dimensions is easier to
# wrap your head around. Here, we first define rows, then a list of rows stacked as columns, then
# a list of columns stacked as levels in a cube.

T = np.array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]
])

print(T.shape)
print(T)

(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


## Tensor Arithmetic

As with matrices, we can perform element-wise arithmetic between tensors.

### Tensor Addition

The element-wise addition of two tensors with the same dimensions results in a new tensor with
the same dimensions where each scalar value is the element-wise addition of the scalars in the
parent tensors.

### C = A + B

In [5]:
# tensor addition
# define first tensor
A = np.array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])

# define second tensor
B = np.array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])

# add tensors
C = A + B
print(C)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


### Tensor Subtraction

The element-wise subtraction of one tensor from another tensor with the same dimensions
results in a new tensor with the same dimensions where each scalar value is the element-wise
subtraction of the scalars in the parent tensors.

### C = A - B

In [6]:
# tensor subtraction
# define first tensor
A = np.array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])

# define second tensor
B = np.array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])

# subtract tensors
C = A - B
print(C)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


### Tensor Hadamard Product

The element-wise multiplication of one tensor with another tensor with the same dimensions
results in a new tensor with the same dimensions where each scalar value is the element-wise
multiplication of the scalars in the parent tensors. As with matrices, the operation is referred to
as the Hadamard Product to di erentiate it from tensor multiplication.

### C = A o B

In [7]:
# tensor Hadamard product
# define first tensor
A = np.array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])

# define second tensor
B = np.array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])

# multiply tensors
C = A * B
print(C)

[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[121 144 169]
  [196 225 256]
  [289 324 361]]

 [[441 484 529]
  [576 625 676]
  [729 784 841]]]


### Tensor Division

The element-wise division of one tensor with another tensor with the same dimensions results in
a new tensor with the same dimensions where each scalar value is the element-wise division of
the scalars in the parent tensors.

### C = A / B

In [9]:
# tensor division
# define first tensor
A = np.array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])

# define second tensor
B = np.array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])

# divide tensors
C = A / B
print(C)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


### Tensor Product

The tensor product operator is often denoted as a circle with a small x in the middle. Given a tensor A with q dimensions and tensor B with r dimensions, the
product of these tensors will be a new tensor with the order of q + r or, said another way, q + r
dimensions. The tensor product is not limited to tensors, but can also be performed on matrices
and vectors, which can be a good place to practice in order to develop the intuition for higher
dimensions.

In [10]:
# tensor product
# define first vector
A = np.array([1,2])

# define second vector
B = np.array([3,4])

# calculate tensor product
C = np.tensordot(A, B, axes=0)
print(C)

[[3 4]
 [6 8]]
