# Vectors

## Defining a vector

In [1]:
import numpy as np

In [2]:
# create a vector
v = np.array([1, 2, 3])
print(v)

[1 2 3]


## Vector arithmetic

Operations are performed element-wise between two vectors of equal length to result in a new vector with the
same length.

### Vector Addition

Two vectors of equal length can be added together to create a new third vector.

c = a + b

The new vector has the same length as the other two vectors. Each element of the new
vector is calculated as the addition of the elements of the other vectors at the same index; for
example:

c = (a1 + b1; a2 + b2; a3 + b3)

In [4]:
#  define first vector
a = np.array([1, 2, 3])
print(a)

# define second vector
b = np.array([1, 2, 3])
print(b)

# add vectors
c = a + b
print(c)

[1 2 3]
[1 2 3]
[2 4 6]


### Vector Subtraction

One vector can be subtracted from another vector of equal length to create a new third vector.

c = a - b

As with addition, the new vector has the same length as the parent vectors and each element
of the new vector is calculated as the subtraction of the elements at the same indices.

c = (a1 - b1; a2 - b2; a3 - b3)

In [6]:
# define first vector
a = np.array([1, 2, 3])
print(a)

# define second vector
b = np.array([0.5, 0.5, 0.5])
print(b)

# subtract vectors
c = a - b
print(c)

[1 2 3]
[0.5 0.5 0.5]
[0.5 1.5 2.5]


### Vector Multiplication

Two vectors of equal length can be multiplied together.

c = a x b

As with addition and subtraction, this operation is performed element-wise to result in a
new vector of the same length.

c = (a1 x b1; a2 x b2; a3 x b3)

or

c = (a1b1, a2b2, a3b3)

In [7]:
# define first vector
a = np.array([1, 2, 3])
print(a)

# define second vector
b = np.array([1, 2, 3])
print(b)

# multiple vectors
c = a * b
print(c)

[1 2 3]
[1 2 3]
[1 4 9]


### Vector Division

Two vectors of equal length can be divided.

c = a/b

As with other arithmetic operations, this operation is performed element-wise to result in a
new vector of the same length.

c = (a1/b1, a2/b2, a3/b3)

In [8]:
# define first vector
a = np.array([1, 2, 3])
print(a)

# define second vector
b = np.array([1, 2, 3])
print(b)

# divide vectors
c = a / b
print(c)

[1 2 3]
[1 2 3]
[1. 1. 1.]


### Vector Dot Product

We can calculate the sum of the multiplied elements of two vectors of the same length to give a
scalar. This is called the dot product, named because of the dot operator used when describing
the operation.

The dot product is a key tool for calculating vector projections, vector decompositions,
and determining orthogonality. The name dot product comes from the symbol
used to denote it.

c = a . b


The operation can be used in machine learning to calculate the weighted sum of a vector.
The dot product is calculated as follows:

c = (a1 x b1 + a2 x b2 + a3 x b3)

or

c = (a1b1 + a2b2 + a3b3)

We can calculate the dot product between two vectors in Python using the dot() function
on a NumPy array.

In [9]:
# define first vector
a = np.array([1, 2, 3])
print(a)

# define second vector
b = np.array([1, 2, 3])
print(b)

# multiple vectors
c = a.dot(b)
print(c)

[1 2 3]
[1 2 3]
14


### Vector-Scalar Multiplication

A vector can be multiplied by a scalar, in effect scaling the magnitude of the vector. To keep
notation simple, we will use lowercase s to represent the scalar value.

c = s x v

or

c = sv

The multiplication is performed on each element of the vector to result in a new scaled
vector of the same length.

c = (s x v1, s x v2, s x v3)

In [10]:
# define vector
a = np.array([1, 2, 3])
print(a)

# define scalar
s = 0.5
print(s)

c = s * a
print(c)

[1 2 3]
0.5
[0.5 1.  1.5]
